---
- name: Ensure db path exists
  file:
    path: '{{ db_path }}'
    state: directory
    owner: 1000
    group: 1000

- name: db_dest_path as fact
  set_fact:
    db_dest_path: '{{ db_path }}/.local/share/polkadot/chains/{{ polkadot_network_id }}'
  when: db_path is defined

- name: download db
  get_url:
    url: '{{ polkadot_db_snapshot_url }}'
    checksum: '{{ polkadot_db_snapshot_checksum | quote }}'
    dest: '{{ db_dest_path }}/db.new.7z'
    mode: '0700'

- name: Stop running validator
  docker_container:
    name: '{{ chain }}'
    state: stopped
  ignore_errors: yes

- name: unpack db
  shell: |
    set -o pipefail
    cd {{ db_dest_path }}
    mv db db.back
    7z x db.new.7z
    rm db.new.7z
    chown -R 1000:1000 db/
  args:
    executable: /bin/bash

- name: Print to start
  ansible.builtin.debug:
    msg: 'Please start your validator again!'