# This playbook deploys a full validator from scratch including downloading a db backup.
# Update the DB download link and checksum in the host_vars first!
---
- name: setup
  hosts: polkadot
  become: yes
  roles:
  - polkadot-setup

- name: Setup polkadot
  hosts: polkadot
  become: yes
  roles:
    - polkadot-restore-db
    - polkadot-validator
    - polkadot-claimer
    - polkadot-rotate-keys

- name: Setup kusama
  hosts: kusama
  become: yes
  roles:
    - polkadot-restore-db
    - polkadot-validator
    - polkadot-claimer
    - polkadot-rotate-keys
