---
- name: Rotate polkadot keys
  hosts: validator1
  become: yes
  roles:
    - polkadot-rotate-keys

- name: Rotate kusama keys
  hosts: validator2
  become: yes
  roles:
    - polkadot-rotate-keys
